export var TEST_MODE_ON = true;
export var STATE_ON = TEST_MODE_ON && true;
export var TEST_FIRST_DAY = new Date(2017, 0, 2);
export var TEST_LAST_DAY = new Date(2019, 0, 31);
export var FIRST_DIOCESI = 0; //0-30 (s'inclou en el test)
export var LAST_DIOCESI = 0; //0-30 (s'inclou en el test)

export default class TestsManager {
  constructor() {
    // require the module
    this.RNFS = require('react-native-fs');

    // create a path you want to write to
    //this.path = this.RNFS.DocumentDirectoryPath + '/test.txt'; //at movile phone
    this.path = '/Users/Pau/Calaix/Projectes/CPL/states/';
    this.filePart = 0;
  }

  writeState(stateArr, idt, fdt, iDt, fDt, cb, lastW) {
    this.filePart++;
    var dataShow = this._transformData(stateArr);

    // write the file
    var idtAux = idt.getDate() + '_' + idt.getMonth() + '_' + idt.getFullYear();
    var fdtAux = fdt.getDate() + '_' + fdt.getMonth() + '_' + fdt.getFullYear();
    var rightNow = new Date();
    var rnDate = rightNow.getDate();
    var rnMonth = rightNow.getMonth() + 1;
    var rnYear = rightNow.getFullYear();
    var plusPath = rnDate + "_" + rnMonth + "_" + rnYear + "-state[" + idtAux + "-" + fdtAux + "," + iDt + "-" + fDt + "]/";
    var name = "state[" + idtAux + "-" + fdtAux + "," + iDt + "-" + fDt + "]Part" + this.filePart + ".txt";
    var totalPath = this.path + plusPath + name;
    this.RNFS.mkdir(this.path + plusPath)
      .then((success) => {
        this.RNFS.writeFile(totalPath, dataShow, 'utf8')
          .then((success) => {
            // console.log('FileLog. FILE WRITTEN!');
            if (lastW) {
              var rightNow = new Date();
              cb("All parts saved correctly at: " + rightNow);
            }
            else {
              cb("File saved correctly. Part: " + this.filePart);
            }
          })
      })
      .catch((err) => {
        console.log('FileLog. Error: ' + err.message);
        cb("File not saved... Error: " + err.message);
      });
  }

  _transformData(SA) {
    var TD = "";
    var x;
    for (x in SA) {
      console.log("FileLog. Part: " + this.filePart + ". Saving the file: " + x + '/' + SA.length);
      TD += '>>>>>' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi;
      TD += '\n>>>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']OFICI';
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']antInvitatori: ' + this.subText(SA[x].LIT.ofici.antInvitatori);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']himne: ' + this.subText(SA[x].LIT.ofici.himne);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']ant1: ' + this.subText(SA[x].LIT.ofici.ant1);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']titol1: ' + this.subText(SA[x].LIT.ofici.titol1);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']com1: ' + this.subText(SA[x].LIT.ofici.com1);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']salm1: ' + this.subText(SA[x].LIT.ofici.salm1);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']gloria1: ' + this.subText(SA[x].LIT.ofici.gloria1);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']ant2: ' + this.subText(SA[x].LIT.ofici.ant2);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']titol2: ' + this.subText(SA[x].LIT.ofici.titol2);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']com2: ' + this.subText(SA[x].LIT.ofici.com2);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']salm2: ' + this.subText(SA[x].LIT.ofici.salm2);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']gloria2: ' + this.subText(SA[x].LIT.ofici.gloria2);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']ant3: ' + this.subText(SA[x].LIT.ofici.ant3);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']titol3: ' + this.subText(SA[x].LIT.ofici.titol3);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']com3: ' + this.subText(SA[x].LIT.ofici.com3);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']salm3: ' + this.subText(SA[x].LIT.ofici.salm3);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']gloria3: ' + this.subText(SA[x].LIT.ofici.gloria3);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']respV: ' + this.subText(SA[x].LIT.ofici.respV);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']respR: ' + this.subText(SA[x].LIT.ofici.respR);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']referencia1: ' + this.subText(SA[x].LIT.ofici.referencia1);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']cita1: ' + this.subText(SA[x].LIT.ofici.cita1);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']titolLectura1: ' + this.subText(SA[x].LIT.ofici.titolLectura1);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']lectura1: ' + this.subText(SA[x].LIT.ofici.lectura1);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']citaResp1: ' + this.subText(SA[x].LIT.ofici.citaResp1);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']resp1Part1: ' + this.subText(SA[x].LIT.ofici.resp1Part1);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']resp1Part2: ' + this.subText(SA[x].LIT.ofici.resp1Part2);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']resp1Part3: ' + this.subText(SA[x].LIT.ofici.resp1Part3);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']referencia2: ' + this.subText(SA[x].LIT.ofici.referencia2);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']cita2: ' + this.subText(SA[x].LIT.ofici.cita2);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']titolLectura2: ' + this.subText(SA[x].LIT.ofici.titolLectura2);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']lectura2: ' + this.subText(SA[x].LIT.ofici.lectura2);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']versResp2: ' + this.subText(SA[x].LIT.ofici.versResp2);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']resp2Part1: ' + this.subText(SA[x].LIT.ofici.resp2Part1);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']resp2Part2: ' + this.subText(SA[x].LIT.ofici.resp2Part2);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']resp2Part3: ' + this.subText(SA[x].LIT.ofici.resp2Part3);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']himneOhDeuBool: ' + this.subText(SA[x].LIT.ofici.himneOhDeuBool);
      TD += '\n';
      TD += '>[Ofici,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']oracio: ' + this.subText(SA[x].LIT.ofici.oracio);
      TD += '\n--------------------';
      TD += '\n>>>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']LAUDES';
      TD += '\n';
      TD += '>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']himne: ' + this.subText(SA[x].LIT.laudes.himne);
      TD += '\n';
      TD += '>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']ant1: ' + this.subText(SA[x].LIT.laudes.ant1);
      TD += '\n';
      TD += '>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']titol1: ' + this.subText(SA[x].LIT.laudes.titol1);
      TD += '\n';
      TD += '>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']com1: ' + this.subText(SA[x].LIT.laudes.com1);
      TD += '\n';
      TD += '>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']salm1: ' + this.subText(SA[x].LIT.laudes.salm1);
      TD += '\n';
      TD += '>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']gloria1: ' + this.subText(SA[x].LIT.laudes.gloria1);
      TD += '\n';
      TD += '>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']ant2: ' + this.subText(SA[x].LIT.laudes.ant2);
      TD += '\n';
      TD += '>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']titol2: ' + this.subText(SA[x].LIT.laudes.titol2);
      TD += '\n';
      TD += '>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']com2: ' + this.subText(SA[x].LIT.laudes.com2);
      TD += '\n';
      TD += '>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']salm2: ' + this.subText(SA[x].LIT.laudes.salm2);
      TD += '\n';
      TD += '>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']gloria2: ' + this.subText(SA[x].LIT.laudes.gloria2);
      TD += '\n';
      TD += '>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']ant3: ' + this.subText(SA[x].LIT.laudes.ant3);
      TD += '\n';
      TD += '>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']titol3: ' + this.subText(SA[x].LIT.laudes.titol3);
      TD += '\n';
      TD += '>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']com3: ' + this.subText(SA[x].LIT.laudes.com3);
      TD += '\n';
      TD += '>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']salm3: ' + this.subText(SA[x].LIT.laudes.salm3);
      TD += '\n';
      TD += '>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']gloria3: ' + this.subText(SA[x].LIT.laudes.gloria3);
      TD += '\n';
      TD += '>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']vers: ' + this.subText(SA[x].LIT.laudes.vers);
      TD += '\n';
      TD += '>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']lecturaBreu: ' + this.subText(SA[x].LIT.laudes.lecturaBreu);
      TD += '\n';
      TD += '>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']calAntEspecial: ' + this.subText(SA[x].LIT.laudes.calAntEspecial);
      TD += '\n';
      TD += '>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']antEspecialLaudes: ' + this.subText(SA[x].LIT.laudes.antEspecialLaudes);
      TD += '\n';
      TD += '>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']respBreu1: ' + this.subText(SA[x].LIT.laudes.respBreu1);
      TD += '\n';
      TD += '>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']respBreu2: ' + this.subText(SA[x].LIT.laudes.respBreu2);
      TD += '\n';
      TD += '>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']respBreu3: ' + this.subText(SA[x].LIT.laudes.respBreu3);
      TD += '\n';
      TD += '>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']antCantic: ' + this.subText(SA[x].LIT.laudes.antCantic);
      TD += '\n';
      TD += '>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']pregaries: ' + this.subText(SA[x].LIT.laudes.pregaries);
      TD += '\n';
      TD += '>[Laudes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']oracio: ' + this.subText(SA[x].LIT.laudes.oracio);
      TD += '\n--------------------';
      TD += '\n>>>[Tercia,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']TERCIA';
      TD += '\n';
      TD += '>[Tercia,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']himne: ' + this.subText(SA[x].LIT.tercia.himne);
      TD += '\n';
      TD += '>[Tercia,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']antifones: ' + this.subText(SA[x].LIT.tercia.antifones);
      TD += '\n';
      TD += '>[Tercia,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']ant: ' + this.subText(SA[x].LIT.tercia.ant);
      TD += '\n';
      TD += '>[Tercia,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']ant1: ' + this.subText(SA[x].LIT.tercia.ant1);
      TD += '\n';
      TD += '>[Tercia,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']titol1: ' + this.subText(SA[x].LIT.tercia.titol1);
      TD += '\n';
      TD += '>[Tercia,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']com1: ' + this.subText(SA[x].LIT.tercia.com1);
      TD += '\n';
      TD += '>[Tercia,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']salm1: ' + this.subText(SA[x].LIT.tercia.salm1);
      TD += '\n';
      TD += '>[Tercia,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']gloria1: ' + this.subText(SA[x].LIT.tercia.gloria1);
      TD += '\n';
      TD += '>[Tercia,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']ant2: ' + this.subText(SA[x].LIT.tercia.ant2);
      TD += '\n';
      TD += '>[Tercia,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']titol2: ' + this.subText(SA[x].LIT.tercia.titol2);
      TD += '\n';
      TD += '>[Tercia,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']com2: ' + this.subText(SA[x].LIT.tercia.com2);
      TD += '\n';
      TD += '>[Tercia,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']salm2: ' + this.subText(SA[x].LIT.tercia.salm2);
      TD += '\n';
      TD += '>[Tercia,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']gloria2: ' + this.subText(SA[x].LIT.tercia.gloria2);
      TD += '\n';
      TD += '>[Tercia,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']ant3: ' + this.subText(SA[x].LIT.tercia.ant3);
      TD += '\n';
      TD += '>[Tercia,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']titol3: ' + this.subText(SA[x].LIT.tercia.titol3);
      TD += '\n';
      TD += '>[Tercia,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']com3: ' + this.subText(SA[x].LIT.tercia.com3);
      TD += '\n';
      TD += '>[Tercia,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']salm3: ' + this.subText(SA[x].LIT.tercia.salm3);
      TD += '\n';
      TD += '>[Tercia,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']gloria3: ' + this.subText(SA[x].LIT.tercia.gloria3);
      TD += '\n';
      TD += '>[Tercia,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']vers: ' + this.subText(SA[x].LIT.tercia.vers);
      TD += '\n';
      TD += '>[Tercia,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']lecturaBreu: ' + this.subText(SA[x].LIT.tercia.lecturaBreu);
      TD += '\n';
      TD += '>[Tercia,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']respV: ' + this.subText(SA[x].LIT.tercia.respV);
      TD += '\n';
      TD += '>[Tercia,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']respR: ' + this.subText(SA[x].LIT.tercia.respR);
      TD += '\n';
      TD += '>[Tercia,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']oracio: ' + this.subText(SA[x].LIT.tercia.oracio);
      TD += '\n--------------------';
      TD += '\n>>>[Sexta,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']SEXTA';
      TD += '\n';
      TD += '>[Sexta,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']himne: ' + this.subText(SA[x].LIT.sexta.himne);
      TD += '\n';
      TD += '>[Sexta,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']antifones: ' + this.subText(SA[x].LIT.sexta.antifones);
      TD += '\n';
      TD += '>[Sexta,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']ant: ' + this.subText(SA[x].LIT.sexta.ant);
      TD += '\n';
      TD += '>[Sexta,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']ant1: ' + this.subText(SA[x].LIT.sexta.ant1);
      TD += '\n';
      TD += '>[Sexta,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']titol1: ' + this.subText(SA[x].LIT.sexta.titol1);
      TD += '\n';
      TD += '>[Sexta,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']com1: ' + this.subText(SA[x].LIT.sexta.com1);
      TD += '\n';
      TD += '>[Sexta,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']salm1: ' + this.subText(SA[x].LIT.sexta.salm1);
      TD += '\n';
      TD += '>[Sexta,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']gloria1: ' + this.subText(SA[x].LIT.sexta.gloria1);
      TD += '\n';
      TD += '>[Sexta,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']ant2: ' + this.subText(SA[x].LIT.sexta.ant2);
      TD += '\n';
      TD += '>[Sexta,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']titol2: ' + this.subText(SA[x].LIT.sexta.titol2);
      TD += '\n';
      TD += '>[Sexta,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']com2: ' + this.subText(SA[x].LIT.sexta.com2);
      TD += '\n';
      TD += '>[Sexta,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']salm2: ' + this.subText(SA[x].LIT.sexta.salm2);
      TD += '\n';
      TD += '>[Sexta,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']gloria2: ' + this.subText(SA[x].LIT.sexta.gloria2);
      TD += '\n';
      TD += '>[Sexta,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']ant3: ' + this.subText(SA[x].LIT.sexta.ant3);
      TD += '\n';
      TD += '>[Sexta,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']titol3: ' + this.subText(SA[x].LIT.sexta.titol3);
      TD += '\n';
      TD += '>[Sexta,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']com3: ' + this.subText(SA[x].LIT.sexta.com3);
      TD += '\n';
      TD += '>[Sexta,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']salm3: ' + this.subText(SA[x].LIT.sexta.salm3);
      TD += '\n';
      TD += '>[Sexta,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']gloria3: ' + this.subText(SA[x].LIT.sexta.gloria3);
      TD += '\n';
      TD += '>[Sexta,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']vers: ' + this.subText(SA[x].LIT.sexta.vers);
      TD += '\n';
      TD += '>[Sexta,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']lecturaBreu: ' + this.subText(SA[x].LIT.sexta.lecturaBreu);
      TD += '\n';
      TD += '>[Sexta,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']respV: ' + this.subText(SA[x].LIT.sexta.respV);
      TD += '\n';
      TD += '>[Sexta,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']respR: ' + this.subText(SA[x].LIT.sexta.respR);
      TD += '\n';
      TD += '>[Sexta,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']oracio: ' + this.subText(SA[x].LIT.sexta.oracio);
      TD += '\n--------------------';
      TD += '\n>>>[Nona,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']NONA';
      TD += '\n';
      TD += '>[Nona,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']himne: ' + this.subText(SA[x].LIT.nona.himne);
      TD += '\n';
      TD += '>[Nona,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']antifones: ' + this.subText(SA[x].LIT.nona.antifones);
      TD += '\n';
      TD += '>[Nona,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']ant: ' + this.subText(SA[x].LIT.nona.ant);
      TD += '\n';
      TD += '>[Nona,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']ant1: ' + this.subText(SA[x].LIT.nona.ant1);
      TD += '\n';
      TD += '>[Nona,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']titol1: ' + this.subText(SA[x].LIT.nona.titol1);
      TD += '\n';
      TD += '>[Nona,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']com1: ' + this.subText(SA[x].LIT.nona.com1);
      TD += '\n';
      TD += '>[Nona,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']salm1: ' + this.subText(SA[x].LIT.nona.salm1);
      TD += '\n';
      TD += '>[Nona,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']gloria1: ' + this.subText(SA[x].LIT.nona.gloria1);
      TD += '\n';
      TD += '>[Nona,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']ant2: ' + this.subText(SA[x].LIT.nona.ant2);
      TD += '\n';
      TD += '>[Nona,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']titol2: ' + this.subText(SA[x].LIT.nona.titol2);
      TD += '\n';
      TD += '>[Nona,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']com2: ' + this.subText(SA[x].LIT.nona.com2);
      TD += '\n';
      TD += '>[Nona,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']salm2: ' + this.subText(SA[x].LIT.nona.salm2);
      TD += '\n';
      TD += '>[Nona,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']gloria2: ' + this.subText(SA[x].LIT.nona.gloria2);
      TD += '\n';
      TD += '>[Nona,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']ant3: ' + this.subText(SA[x].LIT.nona.ant3);
      TD += '\n';
      TD += '>[Nona,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']titol3: ' + this.subText(SA[x].LIT.nona.titol3);
      TD += '\n';
      TD += '>[Nona,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']com3: ' + this.subText(SA[x].LIT.nona.com3);
      TD += '\n';
      TD += '>[Nona,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']salm3: ' + this.subText(SA[x].LIT.nona.salm3);
      TD += '\n';
      TD += '>[Nona,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']gloria3: ' + this.subText(SA[x].LIT.nona.gloria3);
      TD += '\n';
      TD += '>[Nona,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']vers: ' + this.subText(SA[x].LIT.nona.vers);
      TD += '\n';
      TD += '>[Nona,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']lecturaBreu: ' + this.subText(SA[x].LIT.nona.lecturaBreu);
      TD += '\n';
      TD += '>[Nona,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']respV: ' + this.subText(SA[x].LIT.nona.respV);
      TD += '\n';
      TD += '>[Nona,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']respR: ' + this.subText(SA[x].LIT.nona.respR);
      TD += '\n';
      TD += '>[Nona,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']oracio: ' + this.subText(SA[x].LIT.nona.oracio);
      TD += '\n--------------------';
      TD += '\n>>>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']VESPRES';
      TD += '\n';
      TD += '>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']himne: ' + this.subText(SA[x].LIT.vespres.himne);
      TD += '\n';
      TD += '>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']ant1: ' + this.subText(SA[x].LIT.vespres.ant1);
      TD += '\n';
      TD += '>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']titol1: ' + this.subText(SA[x].LIT.vespres.titol1);
      TD += '\n';
      TD += '>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']com1: ' + this.subText(SA[x].LIT.vespres.com1);
      TD += '\n';
      TD += '>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']salm1: ' + this.subText(SA[x].LIT.vespres.salm1);
      TD += '\n';
      TD += '>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']gloria1: ' + this.subText(SA[x].LIT.vespres.gloria1);
      TD += '\n';
      TD += '>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']ant2: ' + this.subText(SA[x].LIT.vespres.ant2);
      TD += '\n';
      TD += '>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']titol2: ' + this.subText(SA[x].LIT.vespres.titol2);
      TD += '\n';
      TD += '>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']com2: ' + this.subText(SA[x].LIT.vespres.com2);
      TD += '\n';
      TD += '>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']salm2: ' + this.subText(SA[x].LIT.vespres.salm2);
      TD += '\n';
      TD += '>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']gloria2: ' + this.subText(SA[x].LIT.vespres.gloria2);
      TD += '\n';
      TD += '>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']ant3: ' + this.subText(SA[x].LIT.vespres.ant3);
      TD += '\n';
      TD += '>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']titol3: ' + this.subText(SA[x].LIT.vespres.titol3);
      TD += '\n';
      TD += '>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']com3: ' + this.subText(SA[x].LIT.vespres.com3);
      TD += '\n';
      TD += '>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']salm3: ' + this.subText(SA[x].LIT.vespres.salm3);
      TD += '\n';
      TD += '>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']gloria3: ' + this.subText(SA[x].LIT.vespres.gloria3);
      TD += '\n';
      TD += '>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']vers: ' + this.subText(SA[x].LIT.vespres.vers);
      TD += '\n';
      TD += '>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']lecturaBreu: ' + this.subText(SA[x].LIT.vespres.lecturaBreu);
      TD += '\n';
      TD += '>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']calAntEspecial: ' + this.subText(SA[x].LIT.vespres.calAntEspecial);
      TD += '\n';
      TD += '>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']antEspecialVespres: ' + this.subText(SA[x].LIT.vespres.antEspecialVespres);
      TD += '\n';
      TD += '>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']respBreu1: ' + this.subText(SA[x].LIT.vespres.respBreu1);
      TD += '\n';
      TD += '>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']respBreu2: ' + this.subText(SA[x].LIT.vespres.respBreu2);
      TD += '\n';
      TD += '>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']respBreu3: ' + this.subText(SA[x].LIT.vespres.respBreu3);
      TD += '\n';
      TD += '>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']antCantic: ' + this.subText(SA[x].LIT.vespres.antCantic);
      TD += '\n';
      TD += '>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']pregaries: ' + this.subText(SA[x].LIT.vespres.pregaries);
      TD += '\n';
      TD += '>[Vespres,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']oracio: ' + this.subText(SA[x].LIT.vespres.oracio);
      TD += '\n--------------------';
      TD += '\n>>>[Completes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']COMPLETES';
      TD += '\n';
      TD += '>[Completes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']himne: ' + this.subText(SA[x].LIT.completes.himne);
      TD += '\n';
      TD += '>[Completes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']antifones: ' + this.subText(SA[x].LIT.completes.antifones);
      TD += '\n';
      TD += '>[Completes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']ant1: ' + this.subText(SA[x].LIT.completes.ant1);
      TD += '\n';
      TD += '>[Completes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']titol1: ' + this.subText(SA[x].LIT.completes.titol1);
      TD += '\n';
      TD += '>[Completes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']com1: ' + this.subText(SA[x].LIT.completes.com1);
      TD += '\n';
      TD += '>[Completes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']salm1: ' + this.subText(SA[x].LIT.completes.salm1);
      TD += '\n';
      TD += '>[Completes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']gloria1: ' + this.subText(SA[x].LIT.completes.gloria1);
      TD += '\n';
      TD += '>[Completes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']ant2: ' + this.subText(SA[x].LIT.completes.ant2);
      TD += '\n';
      TD += '>[Completes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']titol2: ' + this.subText(SA[x].LIT.completes.titol2);
      TD += '\n';
      TD += '>[Completes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']com2: ' + this.subText(SA[x].LIT.completes.com2);
      TD += '\n';
      TD += '>[Completes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']salm2: ' + this.subText(SA[x].LIT.completes.salm2);
      TD += '\n';
      TD += '>[Completes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']gloria2: ' + this.subText(SA[x].LIT.completes.gloria2);
      TD += '\n';
      TD += '>[Completes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']vers: ' + this.subText(SA[x].LIT.completes.vers);
      TD += '\n';
      TD += '>[Completes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']lecturaBreu: ' + this.subText(SA[x].LIT.completes.lecturaBreu);
      TD += '\n';
      TD += '>[Completes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']antRespEspecial: ' + this.subText(SA[x].LIT.completes.antRespEspecial);
      TD += '\n';
      TD += '>[Completes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']respBreu1: ' + this.subText(SA[x].LIT.completes.respBreu1);
      TD += '\n';
      TD += '>[Completes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']respBreu2: ' + this.subText(SA[x].LIT.completes.respBreu2);
      TD += '\n';
      TD += '>[Completes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']respBreu3: ' + this.subText(SA[x].LIT.completes.respBreu3);
      TD += '\n';
      TD += '>[Completes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']antCantic: ' + this.subText(SA[x].LIT.completes.antCantic);
      TD += '\n';
      TD += '>[Completes,' + SA[x].date.day + '/' + SA[x].date.month + '/' + SA[x].date.year + '-' + SA[x].diocesi + ']oracio: ' + this.subText(SA[x].LIT.completes.oracio);
      TD += '\n::---------------------------------------------------::\n';
    }
    console.log("FileLog. TD.length: " + TD.length);
    return TD;
  }

  subText(text) {
    var maxChar = 30; //deixar en blanc si es vol tot el text (var maxChar;)
    if (text && text !== undefined) {
      if (typeof text !== 'string') text = text.toString();
      return text.substring(0, maxChar);
    }
    return "undefined";
  }
}
